name: CI2

on:
  push:
  pull_request:
    branches: [master]

jobs:  
  build-mac:
    runs-on: macos-13
    strategy:
      matrix:
        kernel: [ish, linux]
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Install dependencies
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app
          brew install llvm ninja libarchive
          pip3 install meson
      - name: Clone Linux
        if: matrix.kernel == 'linux'
        run: deps/clone-linux.sh
      - name: Build for ish
        if: matrix.kernel == 'ish'
        run: xcodebuild -project iSH.xcodeproj -scheme iSH -arch arm64 -sdk iphoneos CODE_SIGNING_ALLOWED=NO
      - name: Build for linux
        if: matrix.kernel == 'linux'
        run: xcodebuild -project iSH.xcodeproj -scheme iSH+Linux -arch x86_64 -sdk iphonesimulator CODE_SIGNING_ALLOWED=NO
      - name: Archive to xcarchive
        run: xcodebuild -project iSH.xcodeproj -scheme iSH -configuration Release -archivePath ./Build/iSH.xcarchive archive -sdk iphoneos
      - name: Create IPA
        run: xcodebuild -exportArchive -archivePath ./Build/iSH.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./Build/
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: iSH
          path: ./Build/iSH.ipa
